[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "maais cloud-operations"
restartPolicyType = "NEVER"
overlapSeconds = 0
drainingSeconds = 30

[deploy.multiRegionConfig.europe-west4-drams3a]
numReplicas = 1
